server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jfcdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jfc-consumer-group

# Scheduler configuration
scheduler:
  interval-in-seconds: 2

logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
    kafka: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
